name = "bigsolo-functions"
compatibility_date = "2025-07-13"

[[kv_namespaces]]
binding = "IMG_CHEST_CACHE"
id = "24632818ff5d495e8ec68eb26dd49136"

[[kv_namespaces]]
binding = "INTERACTIONS_LOG"
id = "9bd6247311a141c58512bffb5e133311"

[[kv_namespaces]]
binding = "INTERACTIONS_CACHE"
id = "0653d72f16bb45adb5155e2ea69e5031"

[vars]
ADMIN_USERNAME = ""
ADMIN_PASSWORD = ""